name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Display .NET info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore --verbosity detailed

    - name: Build solution
      run: dotnet build --no-restore --verbosity detailed

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --logger "console;verbosity=detailed"

    - name: Publish artifacts
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet publish LANChat.UI/LANChat.UI.csproj -c Release -o publish --verbosity detailed

    - name: Upload artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: LANChat
        path: publish/**
        retention-days: 5